# Generated by Django 6.0.1 on 2026-01-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Mediam'), ('H', 'High')], default='M', max_length=1),
        ),
    ]
